import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <video  autoPlay loop muted playsInline className='absolute w-full h-full object-cover'>
            <source src="/bg-vid.mp4" type="video/mp4" />
            <source src="/bg-vid.webm" type="video/webm" />
        </video>
    </div>
  )
}
